/*
 * Flight Planner
 *
 * This is a Flight Planner server.
 *
 * API version: 1.0.0
 * Contact: maiarabarroso84@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package handler

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	router.PathPrefix("/").Handler(http.FileServer(http.Dir("./dist")))

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	// Route{
	// 	"Index",
	// 	"GET",
	// 	"/",
	// 	Index,
	// },

	Route{
		"GetFlights",
		strings.ToUpper("Get"),
		"/api/flights",
		getFlights,
	},
	Route{
		"GetCountries",
		strings.ToUpper("Get"),
		"/api/countries",
		getCountries,
	},
	Route{
		"GetCurrencies",
		strings.ToUpper("Get"),
		"/api/currencies",
		getCurrencies,
	},
	Route{
		"GetPlaces",
		strings.ToUpper("Get"),
		"/api/queryPlace",
		getPlaces,
	},
}
